---
- name: Install Jenkins node and Test Server
  hosts: jenkins_nodes:test_servers
  become: yes

  tasks:
  - name: Install Python3-pip
    apt: update_cache=yes name=python3-pip
      
  - name: Upgrade pip3
    shell: sudo -H pip3 install --upgrade pip

  - name: Install Flask
    shell: pip3 install flask

  - name: Install nginx
    apt: update_cache=yes name=nginx state=latest

  - name: Install gunicorn3
    apt: update_cache=yes name=gunicorn3 state=latest

  - name: Create dir deploy-to-test-server-ansible
    shell: mkdir -p /home/ubuntu/jenkins/workspace/deploy-to-test-server-ansible

  - name: Change owner of Jenkins dir
    shell: sudo chgrp -R ubuntu /home/ubuntu/jenkins && sudo chmod -R g+rw /home/ubuntu/jenkins && chown -R ubuntu /home/ubuntu/jenkins

  - name: Create gunicorn3.service and flaskapp.sock
    shell:
     cmd: |
           sudo bash -c 'cat <<EOF > /etc/systemd/system/gunicorn3.service
           [Unit]
           Description=Gunicorn service
           After=network.target

           [Service]
           User=ubuntu
           Group=www-data
           WorkingDirectory=/home/ubuntu/jenkins/workspace/deploy-to-test-server-ansible
           ExecStart=/usr/bin/gunicorn3 --workers 3 --bind unix:flaskapp.sock -m 007 app:app
           EOF'   
    
  - name: Reload daemon
    shell: systemctl daemon-reload
 
  - name: Start gunicorn3.service
    service: name=gunicorn3 state=started enabled=yes

  - name: Configure flaskapp.sock
    shell: 
      cmd: |
           sudo bash -c 'cat <<EOF > /etc/nginx/sites-enabled/flaskapp
           server{
               listen 80;
               server_name 18.217.76.100 18.188.233.6;

               location / {
                   proxy_pass http://unix:/home/ubuntu/jenkins/workspace/deploy-to-test-server-ansible/flaskapp.sock;
               }
           }'

  handlers:
  - name: Restart nginx
    service: name=nginx state=restarted

  - name: Restart gunicorn3
    service: name:=gunicorn3 state=restarted  


